title: Dimitrios Athanasakis - Machine Learning Researcher
description: I'm Dimitrios Athanasakis, a machine learning researcher. This is my personal website, containing research interests, publicatios, and code.
sitename: Home
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
